name: "📌 Task (All-in-One)"
description: 모든 종류의 작업에 사용할 공용 이슈 템플릿
title: "[Type] 한 줄 요약" # 예: [Feat] 로그인 페이지 UI 구현

body:
  # ------------------------------
  # 작업 유형 선택 (커밋 prefix와 동일)
  # ------------------------------
  - type: dropdown
    id: type
    attributes:
      label: 🏷️ Type
      description: "작업 유형을 선택하세요 (커밋 prefix 기준)"
      options:
        - Feat # 새로운 기능 추가
        - Fix # 버그 수정
        - Style # 코드 포맷 변경 (실제 코드 수정 X)
        - Docs # 문서 수정 (README, 주석 등)
        - Refactor # 코드 리팩토링 (기능 변경 없이 구조 개선)
        - Chore # 빌드, 설정, 패키지 설치 등 비기능 작업
    validations:
      required: true

  # ------------------------------
  # 목적/배경
  # ------------------------------
  - type: textarea
    id: context
    attributes:
      label: 🎯 목적/배경
      description: "이 작업이 필요한 이유나 배경을 간단히 작성하세요."
      placeholder: |
        예시)
        - 로그인 기능 구현 전 세션 유효성 검사 로직 필요
        - ESLint 설정이 팀 코드 컨벤션과 일치하지 않음
    validations:
      required: true

  # ------------------------------
  # 본문
  # ------------------------------
  - type: textarea
    id: body
    attributes:
      label: 📋 작업 내용
      description: |
        작업해야 할 내용을 체크리스트 형태로 정리하세요.
        - Feat: 구현할 요구사항 리스트
        - Fix: 재현 단계(1-2-3)와 수정 내용
        - Chore/Refactor: 변경 범위 및 영향
      placeholder: |
        - [ ] 요구사항1
        - [ ] 요구사항2
        - [ ] 테스트 코드 작성
    validations:
      required: true

  # ------------------------------
  # 수용조건 (AC: Acceptance Criteria)
  # ------------------------------
  - type: textarea
    id: ac
    attributes:
      label: ✅ 수용조건 (AC)
      description: "작업 완료 여부를 판단할 수 있는 조건을 작성하세요. (Given-When-Then 형식 권장)"
      placeholder: |
        예시)
        Given 로그인 페이지에서 올바른 정보를 입력하고  
        When 로그인 버튼을 클릭하면  
        Then 메인 페이지로 이동해야 한다.
    validations:
      required: true

  # ------------------------------
  # 참고 정보
  # ------------------------------
  - type: input
    id: links
    attributes:
      label: 🔗 참고 링크 (선택)
      placeholder: "디자인 시안, API 문서, 플로우 차트 등 링크를 추가하세요."

  - type: markdown
    attributes:
      value: |
        ---
        💡 **브랜치 규칙:** `type/{이슈번호-요약}`  
        예) `feat/5-login-ui`  
        커밋 prefix는 다음 중 하나를 사용하세요:  
        **Feat, Fix, Style, Docs, Refactor, Chore**
